### ISSUE TITLE
Implement MultiQueryRetriever and Reranking

### ISSUE THREAD

**Issue by code-Adrastos** [luquelab/ACUNAO-AI#32] opened 2024-08-02 18:31 UTC
"The MultiQueryRetriever automates the process of prompt tuning by using an LLM to generate multiple queries from different perspectives for a given user input query. For each query, it retrieves a set of relevant documents and takes the unique union across all queries to get a larger set of potentially relevant documents. By generating multiple perspectives on the same question, the MultiQueryRetriever might be able to overcome some of the limitations of the distance-based retrieval and get a richer set of results."

"Reranking involves using a more sophisticated model to re-score the documents retrieved by the initial retriever (base retriever/multiqueryretriever)."

Theory:
MultiQueryRetriever generates multiple query variations, which can lead to a more diverse set of initially retrieved documents. Then, a reranker can be used to select the most relevant documents from this expanded set, further improving the overall retrieval accuracy. 

Use Uptrain to check if the theory is correct.

- [x] Implement MultiQueryRetriever
- [x] Display AI-Generated (Refined queries)
- [x] Implement Reranking
- [x] Explore Uptrain and its capabilities i.e. evaluating performance
- [x] Implement Uptrain
- [x] Compare base retriever Vs multiqueryretriever
- [x] Compare reranking Vs multiqueryretriever Vs reranking + multiqueryretriever
- [x] Implement in Streamlit i.e. display the AI-Generated queries so user can see how the AI has understood their query, refined it, and is answering.

**Comment by TjanMichela** [comment] 2024-08-15 16:55
On Monday, August 12, 2024, I created a branch called [feat/32-implement-multiqueryretriever-and-reranking](https://github.com/luquelab/ACUNAO/tree/feat/32-implement-multiqueryretriever-and-reranking) that has reranking added to the RAG System. This branch will remain active for experimentation purposes until it is decided as a team that adding the reranking or any other advanced RAG is effective, efficient, and accurate.

**Comment by TjanMichela** [comment] 2024-11-05 17:06
I am taking over the issue since Latim has no updates since August. The issue is part of exploration, but I expected to get results so that it can be implemented now to improve the AI's responses.

**Comment by TjanMichela** [comment] 2024-11-05 17:48
Implemented both MultiQueryRetriever and Reranking. So far on simple one document, the results are the same, but inference time is slower (from <10secs to >25 secs). Will close this issue and leave the branch open.

**Closed as completed by TjanMichela** 2024-11-05 17:48 UTC
Labels: exploration
